### ISSUE TITLE
Can we have that every new game, ALL categories are preselected?

### ISSUE THREAD

**Issue by RRothfeld** [Redfielder/NeverEver#2]
would be nice. And why is "nsfw = models.BooleanField(default=True)" in model true. on the site it's false for a new game as it should be, is there some contradiction?

**Comment by GeorgiosGoulos** [comment]
yeah, nsfw was supposed to be set to False, I forgot about it when I did changes from sfw to nsfw
As for the categories, I think that this is how it works currently. Unless I misunderstood what you suggested....

**Comment by RRothfeld** [comment]
jep, true, works
